
base:
    APP:
        DATETIME_FORMAT: "%Y-%m-%dT%H%M%S"

    DATA:
        ARTICLE_COUNT_HISTORY:  "data\\Article_Count_History.csv"
        FOLDER: "data"
        FILE_PREFIX: "Pocket_Saves_"

    POCKET:
        POST_REQUEST_URL: "https://getpocket.com/v3/oauth/request"
        POST_REQUEST_REDIRECT_URL: "http://www.google.com"
        POST_AUTHORIZE_URL: "https://getpocket.com/v3/oauth/authorize"
        POST_GET_URL: "https://getpocket.com/v3/get"


    PLOT:
        FOLDER: "data\\plots"
        SAVE_IMAGE_FILE_FORMAT: "Pocket_History_Plot_%Y_%m_%d.png"
        FIGURE_SIZE:
            HORIZ: 10
            VERT: 5
        DATA_LABEL:
            FONT_SIZE: 8
            ROTATION: 45
        ARCHIVE:
            TITLE: "Pocket Archive/Read Article History"
            X_AXIS_TITLE: "Year / This Year As Of Date"
            Y_AXIS_TITLE: "No. of Articles/Year"
        UNREAD:
            TITLE: "No. of Articles/Year"
            X_AXIS_TITLE: "As of Date"
            Y_AXIS_TITLE: "No. of Articles"

    MAX_SAVED_DATA_AGE_DAYS: 7
    MAX_ARTICLE_SUMMARY_RETRIEVAL: 100_000

    LOGGING:
        CONFIG_PATH: "configs/logging_config.yaml"

dev:
    BLANK: 0